export const Users = [
  {
    id: 1,
    profilePicture: "person/1.jpg",
    username: "Jayvee Chavez",
  },
  {
    id: 2,
    profilePicture: "person/2.jpg",
    username: "Rovic Villanueva",
  },
  {
    id: 3,
    profilePicture: "person/12.jpg",
    username: "Roman Dayto",
  },
  {
    id: 4,
    profilePicture: "person/11.jpg",
    username: "Lenard Vico",
  },
  {
    id: 5,
    profilePicture: "person/13.jpg",
    username: "France Madia",
  },
  {
    id: 6,
    profilePicture: "person/14.jpg",
    username: "Eden Noreen",
  },
  {
    id: 7,
    profilePicture: "person/15.jpg",
    username: "Alliah Mandigma",
  },
  {
    id: 8,
    profilePicture: "person/16.jpg",
    username: "Justine Aaron Las",
  },
  {
    id: 9,
    profilePicture: "person/17.jpg",
    username: "Tine Tine",
  },
  {
    id: 10,
    profilePicture: "person/18.jpg",
    username: "Pasilip",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "post/2.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "person/12.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "person/11.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "person/13.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "person/14.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "person/15.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "person/16.jpg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "person/17.jpg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "post/10.jpeg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
